### ISSUE TITLE
how to add and verify the tpm2.0 nv commands in the u-boot

### ISSUE THREAD

**Issue by saravanj24** [joholl/rpi4-uboot-tpm#12]
Hi,

We tried tpm2.0 with u-boot in the raspberry pi4, We are observe the error when run the nv_define command in u-boot. can you tell how to add and verify the nv command in u-boot.

---

CC @tkmozhi

**Comment by joholl** [comment]
Hi, have a look at that link where I patched u-boot to add a TPM command: https://github.com/joholl/rpi4-uboot-tpm/issues/1#issuecomment-694898768

Please also consider submitting your change upstream ;)

**Comment by joholl** [comment]
Btw, mainline u-boot already supports NV define/write/read:
https://source.denx.de/u-boot/u-boot/-/blob/master/lib/tpm-v2.c

You just cannot read/write with policies or authValues (= passwords). The latter could be added easily if that's what you need.

**Comment by saravanj24** [comment]
The below things we tried in the user space for the nvdefine and nv write/read

1.tpm2_nvdefine 0x1500030 -C 0x40000001 -s 10 -a 0x2000A   
2.tpm2_nvwrite 0x1500030 -i - < inputdata
3.tpm2_nvread 0x1500030

with the above steps we can able do the read/write succesfully.

We undefine the nvindex created.

We tried the same above mentioned steps in the u-boot.

We created the do_tpm2_nv_define() to get command as the input to define the nv_index.
  
1. we gave this command for define the nv_index : tpm2 nv_define 0x1500030 32 0x2000A 
2. we defined the nv-policy as NULL in the do_tpm2_nv_define() function.
3. while executing the do_tpm2_nv_define() --> tpm2_nv_define_space(),it responded with the error

       TPM response [ret:725]: 80 01 00 00 00 0a 00 00 02 d5
       Error: 725

Queries: 
1.Is there any specific nv index we should use in the U-boot? 
2.We assigned the owner read/owner write/Policy write in the nv_attributes to define the nv_index? Is there any attributes we need to set?
3.We also tried by setting nv_attributes as owner read/owner write alone, still we are getting same error response as 725.
4.We unable to find the error code details in TPM2.0 source package and also in related docs,suggest where we need to refer this?
5.Is there any other functionalities to be handle to define the nv_index?


Meanwhile we also tried with the which already available in the TPM U-boot package.

we checked with the early_nvram2 command, it failed during nv_write callback with the below error.

U-Boot> tpmtest early_nvram2
argc = 2, argv = tpmtest early_nvram2

Testing earlynavram2...TESTFAILED:line122:tpm_nv_write_value(dev, INDEX0, (uint8_t *)&x, sizeof(x)): 0x284

Is there any update in the test commands for TPM2.0? is there we need to pass any arguments for this test command? is there any reference document available?

**Comment by joholl** [comment]
TL;DR: Either your `do_tpm2_nv_define()` has a bug or you pass bad values.

I broke the `TPM2_NV_DefineSpace` command down to the bytes as an example for you.
```yaml
header:
  .tag: 80 02
  .size: 00 00 00 2d
  .commandCode: 00 00 01 2a

handle: 40 00 00 0c # platform

authArea:
  .size: 00 00 00 09
  .sessionHandle: 40 00 00 09 # password session
  .nonce: 00 00               # empty (size = 0)
  .attributes: 00
  .sessionAuth: 00 00         # empty (size = 0)

auth: 00 00
publicInfo:
  .size: 00 0e
  .nvPublic:
    nvPublic.nvIndex: 01 40 00 01    # arbitrary free NV index
    nvPublic.nameAlg: 00 04          # SHA1
    nvPublic.attributes: 44 04 20 04 # attributes, here TPMA_NV_AUTHREAD | TPMA_NV_POLICYWRITE | TPMA_NV_PLATFORMCREATE
    nvPublic.authPolicy: 00 00       # empty policy (size = 0)
    nvPublic.dataSize: 00 22         # size of the NV space: 34 bytes
```

You can verify this by sending these raw bytes to your TPM (or a TPM simulator, here mssim = Microsoft Simulator):

```bash
echo "80 02 00 00 00 2d 00 00 01 2a 40 00 00 0c 00 00 00 09 40 00 00 09 00 00 00 00 00 00 00 00 0e 01 40 00 01 00 04 44 04 20 04 00 00 00 22" | xxd -r -p | tpm2_send --tcti="mssim" | xxd -p
```

---
> We created the do_tpm2_nv_define() to get command as the input to define the nv_index.

There is already an [API call](https://source.denx.de/u-boot/u-boot/-/blob/master/lib/tpm-v2.c#L84) for defining an NV space in mainline U-Boot. You might want to use that.



---
> 1.Is there any specific nv index we should use in the U-boot?

Have a look at the [reserved indices](https://trustedcomputinggroup.org/wp-content/uploads/RegistryOfReservedTPM2HandlesAndLocalities_v1p1_pub.pdf#%5B%7B%22num%22%3A47%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C33%2C691%2C0%5D). Just use something in the unassigned range: 0x01000000-0x013FFFFF.

---
> 2.We assigned the owner read/owner write/Policy write in the nv_attributes to define the nv_index? Is there any attributes we need to set?

You're basically setting access control options here. That should not impact defining the space. Please refer to the specification for more info.

---
> 3.We also tried by setting nv_attributes as owner read/owner write alone, still we are getting same error response as 725.

See above.

---
> 4.We unable to find the error code details in TPM2.0 source package and also in related docs,suggest where we need to refer this?

You can use the `tpm2-tools` for info about return codes:

```bash
$ tpm2 rc_decode 0x02d5
tpm:parameter(2):structure is the wrong size
```

Basically, that error code is `TPM2_RC_P (0x40) | TPM2_RC_SIZE (0x95)`

From the [TSS definitions](https://github.com/tpm2-software/tpm2-tss/blob/master/include/tss2/tss2_tpm2_types.h):
```c
#define TPM2_RC_FMT1 ((TPM2_RC) 0x080)  /* This bit is SET in all format 1 response codes. The codes in this group may have a value added to them to indicate the handle session or parameter to which they apply. */
#define TPM2_RC_P    ((TPM2_RC) 0x040) /* add to a parameter-related error */
#define TPM2_RC_SIZE ((TPM2_RC) (TPM2_RC_FMT1 + 0x015)) /* structure is the wrong size */
```

This typically means that at least one of the command parameters is malformed.

---
> 5.Is there any other functionalities to be handle to define the nv_index?

Nope, see the example at the top.
